digidem/comapeo-core-react

.prettierignore, docs/API.md, package-lock.json, package.json, src/contexts/ClientApi.ts, src/hooks/client.ts, src/hooks/device-info.ts, src/hooks/documents.ts, src/hooks/maps.ts, src/hooks/projects.ts
Initial attempt at setting up tooling to generate docs based on TS + JSDoc annotations.
Currently uses https://github.com/peterpeterparker/tsdoc-markdown/ to output a single file at `docs/API.md`. The result is pretty barebones but probably sufficient for our needs.
Remaining tasks (many of which will probably be follow-ups):
- Improve examples
- Annotate other public APIs (mostly the lib/react-query stuff)
- Set up a CI workflow to build docs on PRs
=> Set up basic documentation generation flow

docs/API.md, src/contexts/ClientApi.ts, src/hooks/client.ts, src/hooks/documents.ts, src/hooks/maps.ts, src/hooks/projects.ts, src/lib/react-query/documents.ts, src/lib/react-query/projects.ts
Before, we represented options that were passed into the underlying core api as `opts` object, which resulted in us having awkward `opts`-nesting our user-facing APIs. Now we flatten and explicitly specify the parameters of interest, which are still internally passed as an options object to the core apis. This is a notable breaking change.
This PR also:
- updates the TSDoc annotations to better follow [TSDoc](https://tsdoc.org/)
- updates the type annotations to rely less on mirroring types from core internals (e.g. `Parameters<typeof ...>`
=> feat!: flatten api

src/hooks/documents.ts
=> fix: fix type narrowing for document-related hooks

.gitignore, .prettierignore, .tshy/build.json, .tshy/commonjs.json, .tshy/esm.json, package-lock.json, package.json, src/contexts/ClientApi.ts, src/hooks/documents.ts, src/hooks/projects.ts, src/lib/react-query/client.ts, src/lib/react-query/documents.ts, src/lib/react-query/invites.ts, src/lib/react-query/maps.ts, src/lib/react-query/projects.ts, tsconfig.build.json
Consumption of this module is used in a variety of environments where the tooling for module resolution is quite varied e.g:
- Metro, which is primarily CommonJS-first but has improving support for ESM-based modules based on some internal configurations
- Jest, which has limited ESM support out of the box
- Vite
Ideally I wanted to keep this module purely as an ESM-only module, but in early attempts of integrating with our applications (especially React Native), I've found it quite tedious to deal with the headaches of the tools due to differing support of pure ESM modules. To alleviate this headache, this PR introduces [tshy](https://github.com/isaacs/tshy) to set up dual publishing of both ESM and CommonJS. It's quite opinionated but it works sufficiently for the needs of this module.
=> feat: enable usage in both CommonJS and ESM environments

docs/API.md, package.json, src/index.ts
These shouldn't be exposed as they're mostly related to implementation details.
Also updates the API docs to only include exposed contexts and hooks
=> feat!: remove exports for query options

src/lib/react-query/shared.ts
Changes it from `0` to `false`, which shouldn't have any user-facing consequences.
=> chore: update retry option in baseQueryOptions()

docs/API.md, src/hooks/documents.ts, src/index.ts, src/lib/react-query/documents.ts
Closes #20 
Introduces the following write hooks:
- `useCreateDocument()`
- `useUpdateDocument()`
- `useDeleteDocument()`
The idea is for the consuming application to wrap these hooks if they want the convenience of hooks scoped to a writeable data type e.g.
```ts
function useCreateObservation() {
const projectId = useCurrentProjectId()
return useCreateDocument({ docType: 'observation', projectId: projectId })
}
function App() {
const createObservation = useCreateObservation()
function onPress() {
createObservation.mutate({ ... }, { onSuccess: (observationDoc) => { ... } })
}
}
```
Notes:
- Missing in this implementation is being able to specify an `attachmentsToAdd` opts. Since this only applies to observations, I was trying - and failing - to have the implementation elegantly handle the …
=> feat!: implement write hooks for documents

src/lib/react-query/maps.ts
Unlikely to happen, but prevents an issue that would occur if core returns a URL that already has search params and the end-user of the hook uses the `refreshToken` option
=> fix: address edge case for reading map stylejson url

tsconfig.build.json
`tests/` was renamed to `test/` at some point
=> chore: fix tsconfig for build configuration

.github/workflows/ci.yml, docs/CONTRIBUTING.md, package.json, test/helpers/ipc.ts, test/helpers/react.tsx, test/hooks/client.test.tsx, test/hooks/maps.test.tsx, test/setup.ts, vitest.config.js
Introduces tests for hooks related to:
- top-level API client
- maps
Also updates the `test` npm script to only run vitest tests
=> chore(tests): initial tests for hooks

package.json
Although their docs recommend running it on `prepare`, it's annoying and unnecessary in our case that it runs during npm installs. Moving it to `prepack` feels more appropriate for our usage.
=> chore: move tshy to prepack script

docs/API.md, src/contexts/ClientApi.ts
without this, the return type resolves to `React.FunctionComponentElement`, which is a deprecated type.
=> fix: use explicit return type for ClientApiProvider

docs/API.md, src/hooks/projects.ts, src/index.ts, src/lib/react-query/projects.ts, src/lib/sync.ts, test/hooks/projects.test.tsx
Closes #9 
Exposes 4 hooks:
- Read
- `useSyncState()`: get calculated "sync state". directly ported from comapeo-mobile
- `useDataSyncProgress()`: gets calculated progress of `data` sync. directly ported from comapeo-mobile
- Write
- `useStartSync()`: enables sync for a project
- `useStopSync()`: disables sync for a project
Have the beginnings of some tests but definitely not exhaustive. Open to suggestions on how to approach.
=> feat: introduce initial sync hooks

src/hooks/client.ts, src/hooks/documents.ts, src/hooks/invites.ts, src/hooks/projects.ts
Noticed an issue from https://github.com/digidem/comapeo-mobile/pull/1038 where wrapping the `mutate` method with a promise leads to unexpected behavior. The initial reasoning was to avoid needing to expose React Query's `mutateAsync` in the write hooks and let the consumer do the wrapping themselves if needed. However, it seems that wrapping it (like `new Promise((res ,rej) => mutation.mutate(..., { onError: rej, onSuccess: res }))`) doesn't actually work as expected in some specific cases. This is most notable when trying to do parallel mutations. For example:
```tsx
function MutateExample() {
const createDocument = useCreateDocument(...)
const wrapperMutation = useMutation({
mutationFn: async () => {
// Some other work before this
return Promise.all([
new Promise((res, rej) => …
```
=> feat: expose mutateAsync method for write hooks

docs/API.md, package-lock.json, package.json, src/hooks/invites.ts, src/index.ts, src/lib/react-query/invites.ts
Closes #8 
Adds the following hooks:
- `useSetUpInvitesListeners`
- `useSingleInvite`
- `useManyInvites`
Tests have not been implemented yet unfortunately, since it's non-trivial to set up. Will create a new issue to track that work.
This is a breaking change as the hooks are dependent on the updated invites API in core, meaning that `@comapeo/core@3.0.0` (or later) must be used.
=> feat!: add initial invites-related read hooks

package-lock.json, package.json
I erroneously bumped this in #75 despite core still being tied to 1.5.0, causing two installations of it.
=> chore: use correct version of @comapeo/schema in dev deps

package-lock.json, package.json, src/hooks/projects.ts, src/index.ts, src/lib/react-query/projects.ts
Introduces a write hook for removing a server peer from a project. This requires `@comapeo/core@3.1.0`, which is technically a breaking change but I think it's okay to treat it as normal feature add.
=> feat: introduce useRemoveServerPeer hook

docs/API.md, src/lib/react-query/projects.ts
These fields were introduced in `@comapeo/core@3.1.0` (via `@comapeo/schema@1.5.0`)
=> fix: update types for useUpdateProjectSettings to account for project color and description

docs/API.md, package-lock.json, package.json, src/hooks/projects.ts, src/index.ts, src/lib/react-query/projects.ts
Adds `exportGeoJSONFile` and `exportZipFile`
=> feat: new geoJSON and zip file export api

src/lib/react-query/projects.ts
`$originalVersionIdToDeviceId()` maps a versionId to a deviceId. It was a temporary workaround for this information not being included in the docs returned from the server, but it adds RPC round-trip overhead. The result of this query never changes for a given versionId, so it does not need to be refetched and can be cached for ever. Because there are never going to be more than a few hundred deviceIds in a project, I think it's ok to never garbage collect this data, and just keep them cached for ever.
This small change should reduce the number of RPC requests when re-visiting the observation list page.
This is a short-term fix — the longer-term fix is to return a `createdBy` field on docs returned from core, removing the need for the `useDocumentCreatedBy()` hook: …
=> feat: never refetch with `useDocumentCreatedBy()`

src/hooks/projects.ts, src/lib/react-query/projects.ts, src/lib/urls.ts
This is an initial fix for #96. This almost entirely removes RPC requests for icon and attachment URLs, by making a single request for the server port, and then returning all other URLs synchronously.
This includes a "hack" because we do not expose a method for getting the server port, and instead we use the existing `getBlobUrl` method with fake data to parse the port. Because the server lifecycle is maintained by application code, not comapeo-core, it probably doesn't make sense for core to implement an API for the server port, but instead create an API in application code and pass a getPort function to core-react, however that can be a follow-up that requires deeper changes.
This moves logic for URL structure into this library, temporarily, which needs to be kept in sync with the URL …
=> feat: get attachment and icon URLs without async requests

.github/workflows/release.yml
Node LTS has changed to v22, and the optic-release workflow runs in the context of node LTS, not the node version we setup in the previous step.
We are using an older version of better-sqlite3 at the moment, which does not include prebuilds for node v22. It's a dependency of @comapeo/core, which is a dev dep here for tests. better-sqlite3 has a postinstall script that tries to download prebuilds, which is failing on the optic release build command `npm ci`.
This PR adds `--ignore-scripts` to the optic release build command. This would have an impact if any of the modules we are using in our prepack script rely on install scripts running, but I don't think they do, so I think this is safe to do. Hopefully this will unblock us from running the release workflow for now. We will probably need …
=> fix: fix release workflow error from node 22

package-lock.json, package.json
Attempt to release failed (see https://github.com/digidem/comapeo-core-react/actions/runs/17840173969/job/50727388338).
This reverts commit 0230c5eb32485abee8812c86fb8e1b6d861c8b25.
=> Revert "Release v6.2.1 (#116)"

package-lock.json, package.json, src/hooks/documents.ts, src/lib/react-query/documents.ts
`@comapeo/core@4.4.0` introduced the `createdBy` and `updatedBy` fields for data types, which are derived. Without this PR, using the hooks would not expose these fields (in the types) since we're specifying a narrower type annotation that's purely based on the document types defined by schema (i.e. not accounting for derived fields implemented via core).
Ideally we'd make more use of type inference from core for the document-related write hooks, but it results in some kind of ambiguity that prevents TS from resolving the inferred types confidently when trying to build e.g. 
```console
The inferred type of 'useDeleteDocument' cannot be named without a reference to '../../node_modules/rpc-reflector/dist/lib/types.js'. This is likely not portable. A type annotation is necessary.
```
Without …
=> feat: add support for additional derived document fields

src/hooks/projects.ts
Since #125 has been released, there's no longer a need for the `useDocumentCreatedBy` read hook. Adds a deprecation notice for now. We'll eventually remove this entirely when our consuming applications have been updated appropriately.
=> chore: deprecate useDocumentCreatedBy hook
